# Generated by Django 3.0.8 on 2022-07-13 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0001_initial'),
        ('usuario', '0002_usuario_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='instituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_inst', to='instituicao.Instituicao'),
        ),
    ]
