# Generated by Django 3.0.8 on 2022-07-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20220712_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='instituicao',
        ),
    ]
