# Generated by Django 4.1.2 on 2022-12-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.IntegerField(null=True),
        ),
    ]
