# Generated by Django 3.0.8 on 2022-07-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('qtd_espaco', models.IntegerField()),
                ('data_solicitacao', models.DateField()),
                ('horario_requirido', models.TimeField()),
                ('data_agendada', models.DateField()),
                ('origem', models.CharField(max_length=252)),
                ('destino', models.CharField(max_length=252)),
                ('Solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante_user', to='usuario.Usuario')),
            ],
        ),
    ]
