# Generated by Django 3.0.8 on 2022-08-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_instituicao'),
        ('ordem', '0003_auto_20220715_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorista_user', to='usuario.Usuario'),
        ),
    ]
