# Generated by Django 3.0.8 on 2022-08-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_instituicao'),
        ('ordem', '0005_auto_20220815_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='Solicitante',
        ),
        migrations.AddField(
            model_name='ordem',
            name='solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitante_user', to='usuario.Usuario'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
