# Generated by Django 3.0.8 on 2022-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0006_auto_20220815_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='data_solicitacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='horario_requirido',
            field=models.TimeField(auto_now=True),
        ),
    ]
