# Generated by Django 3.0.8 on 2022-08-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0007_auto_20220815_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_ordem', to='ordem.StatusOrdem'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_ordem', to='ordem.StatusOrdem'),
        ),
    ]
