# Generated by Django 3.0.8 on 2022-08-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0003_tipoveiculo_descricao'),
        ('ordem', '0008_auto_20220815_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculo_ordem', to='veiculo.Veiculo'),
        ),
    ]
