# Generated by Django 3.0.8 on 2022-08-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0009_auto_20220815_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='data_agendada',
            field=models.DateField(auto_now_add=True),
        ),
    ]
