# Generated by Django 4.1.2 on 2022-12-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0010_auto_20220815_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statusordem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
