# Generated by Django 4.1.2 on 2022-12-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0011_alter_ordem_id_alter_statusordem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='data_solicitacao',
            field=models.DateField(auto_now=True),
        ),
    ]
