# Generated by Django 4.1.2 on 2022-12-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0012_alter_ordem_data_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='data_solicitado',
            field=models.DateField(null=True),
        ),
    ]
