# Generated by Django 4.1.2 on 2022-12-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0013_ordem_data_solicitado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordem',
            old_name='data_solicitado',
            new_name='data_marcada',
        ),
        migrations.AddField(
            model_name='ordem',
            name='horario_marcado',
            field=models.TimeField(auto_now=True),
        ),
    ]
