# Generated by Django 4.1.2 on 2022-12-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0015_alter_ordem_horario_marcado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='horario_marcado',
            field=models.TimeField(null=True),
        ),
    ]
