# Generated by Django 4.1.2 on 2022-12-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0016_alter_ordem_horario_marcado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='data_agendada',
        ),
        migrations.AddField(
            model_name='ordem',
            name='data_solicitado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='data_solicitacao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='horario_requirido',
            field=models.TimeField(null=True),
        ),
    ]
