# Generated by Django 4.1.2 on 2023-01-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0017_remove_ordem_data_agendada_ordem_data_solicitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='data_solicitado',
            field=models.DateField(null=True),
        ),
    ]
