# Generated by Django 3.0.8 on 2022-07-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_instituicao'),
        ('instituicao', '0004_auto_20220713_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='funcionarios',
            field=models.ManyToManyField(to='usuario.Usuario'),
        ),
    ]
