# Generated by Django 3.0.8 on 2022-09-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20220920_1246'),
        ('instituicao', '0005_auto_20220713_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='instituicao',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CargosInstituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instituicao.Cargo')),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instituicao.Instituicao')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
