# Generated by Django 3.0.8 on 2022-09-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0006_auto_20220921_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='codigo',
            field=models.CharField(default='12345', max_length=10, null=True),
        ),
    ]
