# Generated by Django 4.1.2 on 2022-12-01 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0008_status_alter_cargo_id_alter_cargosinstituicao_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituicao',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='instituicao.status'),
        ),
    ]
