# Generated by Django 4.1.2 on 2022-12-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituicao', '0009_instituicao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargosinstituicao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='funcionarios',
        ),
    ]
