# Generated by Django 3.0.8 on 2022-07-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qtd_pessoas', models.IntegerField()),
                ('placa', models.CharField(max_length=150)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculo.TipoVeiculo')),
            ],
        ),
    ]
