# Generated by Django 3.0.8 on 2022-07-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0002_veiculo_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoveiculo',
            name='descricao',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
