# Generated by Django 4.1.2 on 2023-01-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0004_alter_tipoveiculo_id_alter_veiculo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='image',
            field=models.ImageField(default='defaults/ic_car_image.png', null=True, upload_to='images'),
        ),
    ]
