# Generated by Django 4.1.2 on 2023-01-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0010_alter_veiculo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='image',
            field=models.ImageField(default='defaults/ic_car_image.png', upload_to='images/'),
        ),
    ]
