# Generated by Django 4.1.2 on 2023-01-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0011_alter_veiculo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='image',
            field=models.FileField(blank=True, default='defaults/ic_car_image.png', upload_to='images'),
        ),
    ]
